# EDD2_HW4: COMPAS DATA, QA & ANALYSIS- Time Intensive Assignment

Perform Quality assurance (QA)- generate data dictionaries (3), QA profile and discuss data specifics for https://edd2.s3.amazonaws.com/spring2024/inclass_data/two_year_recidivism.csv and https://edd2.s3.amazonaws.com/spring2024/inclass_data/compas_raw1.csv 

Merge the 2 COMPAS files and discuss merge process. 

Answer the following questions prior to your merge:
- how many columns and rows did you expect in your final file? Why?
- What type of join/merge did you use (inner or outer, left or right)?
 

In [1]:
%run "INCLASS_STARTPY_SETTINGS.ipynb"

IMPORTING BASIC PYTHON LIBRARIES
pandas as pd
numpy as np
matplotlib as plot
seaborn as sns
***********************ENDING LIBRARY IMPORT*****************


# QA - compas_raw1.csv

In [2]:
cp = pd.read_csv('compas_raw1.csv')
cp.info()
cp

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60843 entries, 0 to 60842
Data columns (total 28 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   Person_ID                60843 non-null  int64  
 1   AssessmentID             60843 non-null  int64  
 2   Case_ID                  60843 non-null  int64  
 3   Agency_Text              60843 non-null  object 
 4   LastName                 60843 non-null  object 
 5   FirstName                60843 non-null  object 
 6   MiddleName               15624 non-null  object 
 7   Sex_Code_Text            60843 non-null  object 
 8   Ethnic_Code_Text         60843 non-null  object 
 9   DateOfBirth              60843 non-null  object 
 10  ScaleSet_ID              60843 non-null  int64  
 11  ScaleSet                 60843 non-null  object 
 12  AssessmentReason         60843 non-null  object 
 13  Language                 60843 non-null  object 
 14  LegalStatus           

Person_ID  AssessmentID  Case_ID Agency_Text LastName FirstName  \
0          50844         57167    51950    PRETRIAL   Fisher     Kevin   
1          50844         57167    51950    PRETRIAL   Fisher     Kevin   
2          50844         57167    51950    PRETRIAL   Fisher     Kevin   
3          50848         57174    51956    PRETRIAL  KENDALL     KEVIN   
4          50848         57174    51956    PRETRIAL  KENDALL     KEVIN   
...          ...           ...      ...         ...      ...       ...   
60838      65667         79665    72038   Probation     West     James   
60839      65667         79665    72038   Probation     West     James   
60840      68603         79669    72042    PRETRIAL     Ryan   Michael   
60841      68603         79669    72042    PRETRIAL     Ryan   Michael   
60842      68603         79669    72042    PRETRIAL     Ryan   Michael   

      MiddleName Sex_Code_Text  Ethnic_Code_Text DateOfBirth  ...  \
0            NaN          Male         Caucasian   12/5/1992  ...   
1            NaN          Male         Caucasian   12/5/1992  ...   
2            NaN          Male         Caucasian   12/5/1992  ...   
3            NaN          Male         Caucasian   9/16/1984  ...   
4            NaN          Male         Caucasian   9/16/1984  ...   
...          ...           ...               ...         ...  ...   
60838        NaN          Male  African-American   6/21/1964  ...   
60839        NaN          Male  African-American   6/21/1964  ...   
60840        NaN          Male         Caucasian    2/6/1985  ...   
60841        NaN          Male         Caucasian    2/6/1985  ...   
60842        NaN          Male         Caucasian    2/6/1985  ...   

       RecSupervisionLevel             RecSupervisionLevelText Scale_ID  \
0                        1                                 Low        7   
1                        1                                 Low        8   
2                        1                                 Low       18   
3                        1                                 Low        7   
4                        1                                 Low        8   
...                    ...                                 ...      ...   
60838                    3  Medium with Override Consideration        8   
60839                    3  Medium with Override Consideration       18   
60840                    1                                 Low        7   
60841                    1                                 Low        8   
60842                    1                                 Low       18   

                     DisplayText RawScore DecileScore ScoreText  \
0               Risk of Violence    -2.08           4       Low   
1             Risk of Recidivism    -1.06           2       Low   
2      Risk of Failure to Appear    15.00           1       Low   
3               Risk of Violence    -2.84           2       Low   
4             Risk of Recidivism    -1.50           1       Low   
...                          ...      ...         ...       ...   
60838         Risk of Recidivism     0.16           8      High   
60839  Risk of Failure to Appear    35.00          10      High   
60840           Risk of Violence    -2.75           2       Low   
60841         Risk of Recidivism    -0.34           5    Medium   
60842  Risk of Failure to Appear    16.00           2       Low   

      AssessmentType  IsCompleted IsDeleted  
0                New            1         0  
1                New            1         0  
2                New            1         0  
3                New            1         0  
4                New            1         0  
...              ...          ...       ...  
60838            New            1         0  
60839            New            1         0  
60840            New            1         0  
60841            New            1         0  
60842            New            1         0  

[60843 rows x 28 columns]

### Data Specifics

In [3]:
cp.head()

Person_ID  AssessmentID  Case_ID Agency_Text LastName FirstName MiddleName  \
0      50844         57167    51950    PRETRIAL   Fisher     Kevin        NaN   
1      50844         57167    51950    PRETRIAL   Fisher     Kevin        NaN   
2      50844         57167    51950    PRETRIAL   Fisher     Kevin        NaN   
3      50848         57174    51956    PRETRIAL  KENDALL     KEVIN        NaN   
4      50848         57174    51956    PRETRIAL  KENDALL     KEVIN        NaN   

  Sex_Code_Text Ethnic_Code_Text DateOfBirth  ...  RecSupervisionLevel  \
0          Male        Caucasian   12/5/1992  ...                    1   
1          Male        Caucasian   12/5/1992  ...                    1   
2          Male        Caucasian   12/5/1992  ...                    1   
3          Male        Caucasian   9/16/1984  ...                    1   
4          Male        Caucasian   9/16/1984  ...                    1   

  RecSupervisionLevelText Scale_ID                DisplayText RawScore  \
0                     Low        7           Risk of Violence    -2.08   
1                     Low        8         Risk of Recidivism    -1.06   
2                     Low       18  Risk of Failure to Appear    15.00   
3                     Low        7           Risk of Violence    -2.84   
4                     Low        8         Risk of Recidivism    -1.50   

  DecileScore ScoreText AssessmentType  IsCompleted IsDeleted  
0           4       Low            New            1         0  
1           2       Low            New            1         0  
2           1       Low            New            1         0  
3           2       Low            New            1         0  
4           1       Low            New            1         0  

[5 rows x 28 columns]

In [4]:
cp.isnull().sum()

Person_ID                      0
AssessmentID                   0
Case_ID                        0
Agency_Text                    0
LastName                       0
FirstName                      0
MiddleName                 45219
Sex_Code_Text                  0
Ethnic_Code_Text               0
DateOfBirth                    0
ScaleSet_ID                    0
ScaleSet                       0
AssessmentReason               0
Language                       0
LegalStatus                    0
CustodyStatus                  0
MaritalStatus                  0
Screening_Date                 0
RecSupervisionLevel            0
RecSupervisionLevelText        0
Scale_ID                       0
DisplayText                    0
RawScore                       0
DecileScore                    0
ScoreText                     45
AssessmentType                 0
IsCompleted                    0
IsDeleted                      0
dtype: int64

In [5]:
cp.dtypes

Person_ID                    int64
AssessmentID                 int64
Case_ID                      int64
Agency_Text                 object
LastName                    object
FirstName                   object
MiddleName                  object
Sex_Code_Text               object
Ethnic_Code_Text            object
DateOfBirth                 object
ScaleSet_ID                  int64
ScaleSet                    object
AssessmentReason            object
Language                    object
LegalStatus                 object
CustodyStatus               object
MaritalStatus               object
Screening_Date              object
RecSupervisionLevel          int64
RecSupervisionLevelText     object
Scale_ID                     int64
DisplayText                 object
RawScore                   float64
DecileScore                  int64
ScoreText                   object
AssessmentType              object
IsCompleted                  int64
IsDeleted                    int64
dtype: object

In [6]:
cp.Sex_Code_Text.unique()

array(['Male', 'Female'], dtype=object)

In [7]:
cp.DisplayText.unique()

array(['Risk of Violence', 'Risk of Recidivism',
       'Risk of Failure to Appear'], dtype=object)

### Check for a one-to-many relationship using Person_id

In [8]:
gropupeddata=cp.groupby('Person_ID').size()
gropupeddata

Person_ID
656      3
667      3
684      3
737      3
745      3
        ..
68600    3
68602    3
68603    3
68604    3
68608    3
Length: 18610, dtype: int64

In [9]:
onetomany=gropupeddata[gropupeddata>1]
onetomany

Person_ID
656      3
667      3
684      3
737      3
745      3
        ..
68600    3
68602    3
68603    3
68604    3
68608    3
Length: 18610, dtype: int64

In [10]:
gropupeddata.describe(percentiles={.1,.2,.3,.4,.5,.6,.7,.8,.9})

count    18610.000000
mean         3.269371
std          0.940507
min          3.000000
10%          3.000000
20%          3.000000
30%          3.000000
40%          3.000000
50%          3.000000
60%          3.000000
70%          3.000000
80%          3.000000
90%          3.000000
max         12.000000
dtype: float64

Clearly there seems to be a one to many problem, some prisoners appear up to 12 times!

In [11]:
#fixing the date situation - ugh!
from datetime import datetime
#cp['DateOfBirth'].str.split("/",3) basic command for spliting a dataframe column with a delimiter
print("let's understand the year structure and apply domain knowledge")
cp[['month','day','year']]= cp['DateOfBirth'].str.split("/", expand=True)
cp

let's understand the year structure and apply domain knowledge


Person_ID  AssessmentID  Case_ID Agency_Text LastName FirstName  \
0          50844         57167    51950    PRETRIAL   Fisher     Kevin   
1          50844         57167    51950    PRETRIAL   Fisher     Kevin   
2          50844         57167    51950    PRETRIAL   Fisher     Kevin   
3          50848         57174    51956    PRETRIAL  KENDALL     KEVIN   
4          50848         57174    51956    PRETRIAL  KENDALL     KEVIN   
...          ...           ...      ...         ...      ...       ...   
60838      65667         79665    72038   Probation     West     James   
60839      65667         79665    72038   Probation     West     James   
60840      68603         79669    72042    PRETRIAL     Ryan   Michael   
60841      68603         79669    72042    PRETRIAL     Ryan   Michael   
60842      68603         79669    72042    PRETRIAL     Ryan   Michael   

      MiddleName Sex_Code_Text  Ethnic_Code_Text DateOfBirth  ...  \
0            NaN          Male         Caucasian   12/5/1992  ...   
1            NaN          Male         Caucasian   12/5/1992  ...   
2            NaN          Male         Caucasian   12/5/1992  ...   
3            NaN          Male         Caucasian   9/16/1984  ...   
4            NaN          Male         Caucasian   9/16/1984  ...   
...          ...           ...               ...         ...  ...   
60838        NaN          Male  African-American   6/21/1964  ...   
60839        NaN          Male  African-American   6/21/1964  ...   
60840        NaN          Male         Caucasian    2/6/1985  ...   
60841        NaN          Male         Caucasian    2/6/1985  ...   
60842        NaN          Male         Caucasian    2/6/1985  ...   

                     DisplayText RawScore DecileScore ScoreText  \
0               Risk of Violence    -2.08           4       Low   
1             Risk of Recidivism    -1.06           2       Low   
2      Risk of Failure to Appear    15.00           1       Low   
3               Risk of Violence    -2.84           2       Low   
4             Risk of Recidivism    -1.50           1       Low   
...                          ...      ...         ...       ...   
60838         Risk of Recidivism     0.16           8      High   
60839  Risk of Failure to Appear    35.00          10      High   
60840           Risk of Violence    -2.75           2       Low   
60841         Risk of Recidivism    -0.34           5    Medium   
60842  Risk of Failure to Appear    16.00           2       Low   

      AssessmentType IsCompleted IsDeleted month  day  year  
0                New           1         0    12    5  1992  
1                New           1         0    12    5  1992  
2                New           1         0    12    5  1992  
3                New           1         0     9   16  1984  
4                New           1         0     9   16  1984  
...              ...         ...       ...   ...  ...   ...  
60838            New           1         0     6   21  1964  
60839            New           1         0     6   21  1964  
60840            New           1         0     2    6  1985  
60841            New           1         0     2    6  1985  
60842            New           1         0     2    6  1985  

[60843 rows x 31 columns]

In [12]:
cp.year.astype(int).describe()

count    60843.000000
mean      1979.341847
std         12.162173
min       1930.000000
25%       1971.000000
50%       1982.000000
75%       1989.000000
max       2029.000000
Name: year, dtype: float64

In [13]:
print(" first lets convert the object/string year into an integer to understand the distribution")
cp.year.astype(int).describe(percentiles={.005,0.02,.1,.2,.3,.4,.5,.6,.7,.8,.9})

 first lets convert the object/string year into an integer to understand the distribution


count    60843.000000
mean      1979.341847
std         12.162173
min       1930.000000
0.5%      1944.000000
2%        1951.000000
10%       1961.000000
20%       1968.000000
30%       1974.000000
40%       1979.000000
50%       1982.000000
60%       1985.000000
70%       1988.000000
80%       1990.000000
90%       1993.000000
max       2029.000000
Name: year, dtype: float64

In [14]:
cp['year'].isnull().sum()

0

Convert the columns the first two numbers of the rows with 2005 and higher to 19, since it may have been a typo.

In [15]:
cp['year']='19' + cp.year.str[-2:]
cp

Person_ID  AssessmentID  Case_ID Agency_Text LastName FirstName  \
0          50844         57167    51950    PRETRIAL   Fisher     Kevin   
1          50844         57167    51950    PRETRIAL   Fisher     Kevin   
2          50844         57167    51950    PRETRIAL   Fisher     Kevin   
3          50848         57174    51956    PRETRIAL  KENDALL     KEVIN   
4          50848         57174    51956    PRETRIAL  KENDALL     KEVIN   
...          ...           ...      ...         ...      ...       ...   
60838      65667         79665    72038   Probation     West     James   
60839      65667         79665    72038   Probation     West     James   
60840      68603         79669    72042    PRETRIAL     Ryan   Michael   
60841      68603         79669    72042    PRETRIAL     Ryan   Michael   
60842      68603         79669    72042    PRETRIAL     Ryan   Michael   

      MiddleName Sex_Code_Text  Ethnic_Code_Text DateOfBirth  ...  \
0            NaN          Male         Caucasian   12/5/1992  ...   
1            NaN          Male         Caucasian   12/5/1992  ...   
2            NaN          Male         Caucasian   12/5/1992  ...   
3            NaN          Male         Caucasian   9/16/1984  ...   
4            NaN          Male         Caucasian   9/16/1984  ...   
...          ...           ...               ...         ...  ...   
60838        NaN          Male  African-American   6/21/1964  ...   
60839        NaN          Male  African-American   6/21/1964  ...   
60840        NaN          Male         Caucasian    2/6/1985  ...   
60841        NaN          Male         Caucasian    2/6/1985  ...   
60842        NaN          Male         Caucasian    2/6/1985  ...   

                     DisplayText RawScore DecileScore ScoreText  \
0               Risk of Violence    -2.08           4       Low   
1             Risk of Recidivism    -1.06           2       Low   
2      Risk of Failure to Appear    15.00           1       Low   
3               Risk of Violence    -2.84           2       Low   
4             Risk of Recidivism    -1.50           1       Low   
...                          ...      ...         ...       ...   
60838         Risk of Recidivism     0.16           8      High   
60839  Risk of Failure to Appear    35.00          10      High   
60840           Risk of Violence    -2.75           2       Low   
60841         Risk of Recidivism    -0.34           5    Medium   
60842  Risk of Failure to Appear    16.00           2       Low   

      AssessmentType IsCompleted IsDeleted month  day  year  
0                New           1         0    12    5  1992  
1                New           1         0    12    5  1992  
2                New           1         0    12    5  1992  
3                New           1         0     9   16  1984  
4                New           1         0     9   16  1984  
...              ...         ...       ...   ...  ...   ...  
60838            New           1         0     6   21  1964  
60839            New           1         0     6   21  1964  
60840            New           1         0     2    6  1985  
60841            New           1         0     2    6  1985  
60842            New           1         0     2    6  1985  

[60843 rows x 31 columns]

In [16]:
cp_date=cp[['Screening_Date']]
cp_date

Screening_Date
0        1/1/2013 0:00
1        1/1/2013 0:00
2        1/1/2013 0:00
3        1/1/2013 0:00
4        1/1/2013 0:00
...                ...
60838  12/31/2014 0:00
60839  12/31/2014 0:00
60840  12/31/2014 0:00
60841  12/31/2014 0:00
60842  12/31/2014 0:00

[60843 rows x 1 columns]

In [17]:
cp['Screening_Date'].isnull().sum()

0

In [18]:
print("now that we understand the datetime format required %m/%d/%y %H:%M")
print("Let's convert it! First we convert of date of birth/dob and then the screening date followed by the age calculation")
print("what does the new age distribution look like...")
cp['dob']=pd.to_datetime(cp[['month','day','year']]).dt.date

now that we understand the datetime format required %m/%d/%y %H:%M
Let's convert it! First we convert of date of birth/dob and then the screening date followed by the age calculation
what does the new age distribution look like...


In [19]:
cp['scrdte']=pd.to_datetime(cp.Screening_Date).dt.date
cp['age'] = ((cp['scrdte'] - cp['dob']) / np.timedelta64(1, 'D') / 365.25).round().astype(int)
cp.age.describe(percentiles={0.025,0.05,.1,.2,.3,.4,.5,.6,.7,.8,.9})

count    60843.000000
mean        34.113801
std         12.179684
min         16.000000
2.5%        19.000000
5%          19.000000
10%         21.000000
20%         23.000000
30%         25.000000
40%         28.000000
50%         31.000000
60%         35.000000
70%         39.000000
80%         46.000000
90%         52.000000
max         94.000000
Name: age, dtype: float64

Now that I move into the analysis of DecileScores let's analyze the unique values.

In [20]:
cp['DecileScore'].unique()

array([ 4,  2,  1,  3,  8,  7,  6, 10,  9,  5, -1], dtype=int64)

In [21]:
cp_1= cp[cp['DecileScore'] == -1]
cp_1.head()

Person_ID  AssessmentID  Case_ID Agency_Text LastName FirstName  \
1837      51351         57821    52534    PRETRIAL    Taffe    Horace   
4033      51986         58599    53245    PRETRIAL     Farr      Clee   
6603      52760         59586    54136   Probation     Diaz   Jahaira   
6604      52760         59586    54136   Probation     Diaz   Jahaira   
7173      52910         59783    54307    PRETRIAL   MILLER   MIKHAIL   

     MiddleName Sex_Code_Text  Ethnic_Code_Text DateOfBirth  ...  ScoreText  \
1837        NaN          Male  African-American  11/28/1971  ...        NaN   
4033        NaN          Male         Caucasian  12/22/1995  ...        NaN   
6603        NaN        Female          Hispanic   1/16/1981  ...        NaN   
6604        NaN        Female          Hispanic   1/16/1981  ...        NaN   
7173    LEONARD          Male  African-American  10/12/1993  ...        NaN   

     AssessmentType IsCompleted IsDeleted month day  year         dob  \
1837            New           1         0    11  28  1971  1971-11-28   
4033            New           1         0    12  22  1995  1995-12-22   
6603            New           1         0     1  16  1981  1981-01-16   
6604            New           1         0     1  16  1981  1981-01-16   
7173            New           1         0    10  12  1993  1993-10-12   

          scrdte age  
1837  2013-01-18  41  
4033  2013-02-08  17  
6603  2013-03-06  32  
6604  2013-03-06  32  
7173  2013-03-12  19  

[5 rows x 34 columns]

In [22]:
cp_nan=cp[cp['ScoreText'].isna()]
cp_nan.head()

Person_ID  AssessmentID  Case_ID Agency_Text LastName FirstName  \
1837      51351         57821    52534    PRETRIAL    Taffe    Horace   
4033      51986         58599    53245    PRETRIAL     Farr      Clee   
6603      52760         59586    54136   Probation     Diaz   Jahaira   
6604      52760         59586    54136   Probation     Diaz   Jahaira   
7173      52910         59783    54307    PRETRIAL   MILLER   MIKHAIL   

     MiddleName Sex_Code_Text  Ethnic_Code_Text DateOfBirth  ...  ScoreText  \
1837        NaN          Male  African-American  11/28/1971  ...        NaN   
4033        NaN          Male         Caucasian  12/22/1995  ...        NaN   
6603        NaN        Female          Hispanic   1/16/1981  ...        NaN   
6604        NaN        Female          Hispanic   1/16/1981  ...        NaN   
7173    LEONARD          Male  African-American  10/12/1993  ...        NaN   

     AssessmentType IsCompleted IsDeleted month day  year         dob  \
1837            New           1         0    11  28  1971  1971-11-28   
4033            New           1         0    12  22  1995  1995-12-22   
6603            New           1         0     1  16  1981  1981-01-16   
6604            New           1         0     1  16  1981  1981-01-16   
7173            New           1         0    10  12  1993  1993-10-12   

          scrdte age  
1837  2013-01-18  41  
4033  2013-02-08  17  
6603  2013-03-06  32  
6604  2013-03-06  32  
7173  2013-03-12  19  

[5 rows x 34 columns]

In [23]:
are_equal= cp_1.equals(cp_nan)
are_equal

True

I will drop the rows for which Decile Score is negative 1 which reflects the nan values in ScoreText column.

In [24]:
cp = cp[cp['ScoreText'].notna() & (cp['DecileScore'] != -1)]
cp.head()

Person_ID  AssessmentID  Case_ID Agency_Text LastName FirstName MiddleName  \
0      50844         57167    51950    PRETRIAL   Fisher     Kevin        NaN   
1      50844         57167    51950    PRETRIAL   Fisher     Kevin        NaN   
2      50844         57167    51950    PRETRIAL   Fisher     Kevin        NaN   
3      50848         57174    51956    PRETRIAL  KENDALL     KEVIN        NaN   
4      50848         57174    51956    PRETRIAL  KENDALL     KEVIN        NaN   

  Sex_Code_Text Ethnic_Code_Text DateOfBirth  ...  ScoreText AssessmentType  \
0          Male        Caucasian   12/5/1992  ...        Low            New   
1          Male        Caucasian   12/5/1992  ...        Low            New   
2          Male        Caucasian   12/5/1992  ...        Low            New   
3          Male        Caucasian   9/16/1984  ...        Low            New   
4          Male        Caucasian   9/16/1984  ...        Low            New   

  IsCompleted IsDeleted month day  year         dob      scrdte age  
0           1         0    12   5  1992  1992-12-05  2013-01-01  20  
1           1         0    12   5  1992  1992-12-05  2013-01-01  20  
2           1         0    12   5  1992  1992-12-05  2013-01-01  20  
3           1         0     9  16  1984  1984-09-16  2013-01-01  28  
4           1         0     9  16  1984  1984-09-16  2013-01-01  28  

[5 rows x 34 columns]

In [25]:
cp.DisplayText.value_counts()

DisplayText
Risk of Failure to Appear    20281
Risk of Violence             20272
Risk of Recidivism           20245
Name: count, dtype: int64

Screening date set on ascending false is crucial here because we want to get rid of the 1 to many problem, so by by ordering by screening date we can choose the first instance a person went to jail.

In [26]:
cp1=cp.copy(deep=True)
cp1=cp1.sort_values(by=['Person_ID','Screening_Date','DisplayText'], ascending=[True,False,True])
cp1['ID_CUMCNT']=cp1.groupby(['Person_ID']).cumcount()
cp1.head()


Person_ID  AssessmentID  Case_ID     Agency_Text LastName FirstName  \
47996        656         74859      350  Broward County    DAVIS   LAKISHA   
47995        656         74859      350  Broward County    DAVIS   LAKISHA   
47994        656         74859      350  Broward County    DAVIS   LAKISHA   
48596        667         75075    67999  Broward County    RICKS     DEVON   
48595        667         75075    67999  Broward County    RICKS     DEVON   

      MiddleName Sex_Code_Text  Ethnic_Code_Text DateOfBirth  ...  \
47996    LATRICE        Female  African-American   1/20/1981  ...   
47995    LATRICE        Female  African-American   1/20/1981  ...   
47994    LATRICE        Female  African-American   1/20/1981  ...   
48596        NaN          Male  African-American  11/25/1988  ...   
48595        NaN          Male  African-American  11/25/1988  ...   

       AssessmentType IsCompleted IsDeleted month day  year         dob  \
47996            Copy           1         0     1  20  1981  1981-01-20   
47995            Copy           1         0     1  20  1981  1981-01-20   
47994            Copy           1         0     1  20  1981  1981-01-20   
48596             New           1         0    11  25  1988  1988-11-25   
48595             New           1         0    11  25  1988  1988-11-25   

           scrdte  age ID_CUMCNT  
47996  2014-07-13   33         0  
47995  2014-07-13   33         1  
47994  2014-07-13   33         2  
48596  2014-07-20   26         0  
48595  2014-07-20   26         1  

[5 rows x 35 columns]

### One to many problem fix

In [27]:
print("Create a subset that accounts for the 1: Many or 1:3+ problem.")
cp1_aboveavg1=cp1[cp1.ID_CUMCNT<=2]
cp1_aboveavg1[['Person_ID','DisplayText','Screening_Date','ID_CUMCNT']]
cp2=cp1[cp1.ID_CUMCNT<=2]
cp2

Create a subset that accounts for the 1: Many or 1:3+ problem.


Person_ID  AssessmentID  Case_ID     Agency_Text LastName FirstName  \
47996        656         74859      350  Broward County    DAVIS   LAKISHA   
47995        656         74859      350  Broward County    DAVIS   LAKISHA   
47994        656         74859      350  Broward County    DAVIS   LAKISHA   
48596        667         75075    67999  Broward County    RICKS     DEVON   
48595        667         75075    67999  Broward County    RICKS     DEVON   
...          ...           ...      ...             ...      ...       ...   
60793      68604         79671    72043        PRETRIAL  Sookram   krishna   
60792      68604         79671    72043        PRETRIAL  Sookram   krishna   
60827      68608         79677    72045        PRETRIAL    Hayes    Thomas   
60826      68608         79677    72045        PRETRIAL    Hayes    Thomas   
60825      68608         79677    72045        PRETRIAL    Hayes    Thomas   

      MiddleName Sex_Code_Text  Ethnic_Code_Text DateOfBirth  ...  \
47996    LATRICE        Female  African-American   1/20/1981  ...   
47995    LATRICE        Female  African-American   1/20/1981  ...   
47994    LATRICE        Female  African-American   1/20/1981  ...   
48596        NaN          Male  African-American  11/25/1988  ...   
48595        NaN          Male  African-American  11/25/1988  ...   
...          ...           ...               ...         ...  ...   
60793        NaN          Male         Caucasian   8/15/1984  ...   
60792        NaN          Male         Caucasian   8/15/1984  ...   
60827        NaN          Male         Caucasian   8/13/1989  ...   
60826        NaN          Male         Caucasian   8/13/1989  ...   
60825        NaN          Male         Caucasian   8/13/1989  ...   

       AssessmentType IsCompleted IsDeleted month day  year         dob  \
47996            Copy           1         0     1  20  1981  1981-01-20   
47995            Copy           1         0     1  20  1981  1981-01-20   
47994            Copy           1         0     1  20  1981  1981-01-20   
48596             New           1         0    11  25  1988  1988-11-25   
48595             New           1         0    11  25  1988  1988-11-25   
...               ...         ...       ...   ...  ..   ...         ...   
60793             New           1         0     8  15  1984  1984-08-15   
60792             New           1         0     8  15  1984  1984-08-15   
60827             New           1         0     8  13  1989  1989-08-13   
60826             New           1         0     8  13  1989  1989-08-13   
60825             New           1         0     8  13  1989  1989-08-13   

           scrdte  age ID_CUMCNT  
47996  2014-07-13   33         0  
47995  2014-07-13   33         1  
47994  2014-07-13   33         2  
48596  2014-07-20   26         0  
48595  2014-07-20   26         1  
...           ...  ...       ...  
60793  2014-12-31   30         1  
60792  2014-12-31   30         2  
60827  2014-12-31   25         0  
60826  2014-12-31   25         1  
60825  2014-12-31   25         2  

[55793 rows x 35 columns]

## Clean Up Categorical Features For Data Profile

In [28]:
from sklearn.preprocessing import LabelEncoder

In [29]:
fix_sex_dict={'Male' :0, 'Female' :1}
cp2['gender1']=cp2.Sex_Code_Text.map(fix_sex_dict)
cp2[['Sex_Code_Text','gender1']].groupby(['Sex_Code_Text'])['gender1'].value_counts()

C:\Users\pablo\AppData\Local\Temp\ipykernel_10220\3730255889.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cp2['gender1']=cp2.Sex_Code_Text.map(fix_sex_dict)


Sex_Code_Text  gender1
Female         1          12494
Male           0          43299
Name: count, dtype: int64

In [30]:
fix_lang_dict={'English' :0, 'Spanish' :1}
cp2['Language_1']=cp2.Language.map(fix_lang_dict)
cp2[['Language','Language_1']].groupby(['Language'])['Language_1'].value_counts()

C:\Users\pablo\AppData\Local\Temp\ipykernel_10220\4065148954.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cp2['Language_1']=cp2.Language.map(fix_lang_dict)


Language  Language_1
English   0             55547
Spanish   1               246
Name: count, dtype: int64

In [31]:
cp2['MaritalStatus'].value_counts()

MaritalStatus
Single               41127
Married               7674
Divorced              3598
Separated             1661
Significant Other     1160
Widowed                363
Unknown                210
Name: count, dtype: int64

In [32]:
def encode_marital_status_binary(cp):
    if cp.MaritalStatus in ["Married", "Significant Other"]:
        return 1
    else:
        return 0

cp2['MaritalStatusBinary'] = cp2.apply(encode_marital_status_binary, axis=1)
cp2.head()

C:\Users\pablo\AppData\Local\Temp\ipykernel_10220\1911571834.py:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cp2['MaritalStatusBinary'] = cp2.apply(encode_marital_status_binary, axis=1)


Person_ID  AssessmentID  Case_ID     Agency_Text LastName FirstName  \
47996        656         74859      350  Broward County    DAVIS   LAKISHA   
47995        656         74859      350  Broward County    DAVIS   LAKISHA   
47994        656         74859      350  Broward County    DAVIS   LAKISHA   
48596        667         75075    67999  Broward County    RICKS     DEVON   
48595        667         75075    67999  Broward County    RICKS     DEVON   

      MiddleName Sex_Code_Text  Ethnic_Code_Text DateOfBirth  ...  month day  \
47996    LATRICE        Female  African-American   1/20/1981  ...      1  20   
47995    LATRICE        Female  African-American   1/20/1981  ...      1  20   
47994    LATRICE        Female  African-American   1/20/1981  ...      1  20   
48596        NaN          Male  African-American  11/25/1988  ...     11  25   
48595        NaN          Male  African-American  11/25/1988  ...     11  25   

       year         dob      scrdte age ID_CUMCNT gender1  Language_1  \
47996  1981  1981-01-20  2014-07-13  33         0       1           0   
47995  1981  1981-01-20  2014-07-13  33         1       1           0   
47994  1981  1981-01-20  2014-07-13  33         2       1           0   
48596  1988  1988-11-25  2014-07-20  26         0       0           0   
48595  1988  1988-11-25  2014-07-20  26         1       0           0   

      MaritalStatusBinary  
47996                   0  
47995                   0  
47994                   0  
48596                   0  
48595                   0  

[5 rows x 38 columns]

In [33]:
cp2['Ethnic_Code_Text'].value_counts()

Ethnic_Code_Text
African-American    24323
Caucasian           20212
Hispanic             8175
Other                2423
Asian                 312
Native American       195
Arabic                 75
African-Am             39
Oriental               39
Name: count, dtype: int64

In [34]:
def encode_ethnicity(cp):
    if cp.Ethnic_Code_Text in ["African-American", "African-Am"]:
        return 0
    elif cp.Ethnic_Code_Text == "Caucasian":
        return 1
    elif cp.Ethnic_Code_Text == "Hispanic":
        return 2
    elif cp.Ethnic_Code_Text in ["Asian", "Oriental"]:
        return 3
    elif cp.Ethnic_Code_Text == "Other":
        return 4
    elif cp.Ethnic_Code_Text == "Native American":
        return 5
    elif cp.Ethnic_Code_Text == "Arabic":
        return 6
    else:
        return 99  # Default value for unexpected categories

cp2['EthnicCodeEncoded'] = cp2.apply(encode_ethnicity, axis=1)
cp2.head()

C:\Users\pablo\AppData\Local\Temp\ipykernel_10220\3027517006.py:19: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cp2['EthnicCodeEncoded'] = cp2.apply(encode_ethnicity, axis=1)


Person_ID  AssessmentID  Case_ID     Agency_Text LastName FirstName  \
47996        656         74859      350  Broward County    DAVIS   LAKISHA   
47995        656         74859      350  Broward County    DAVIS   LAKISHA   
47994        656         74859      350  Broward County    DAVIS   LAKISHA   
48596        667         75075    67999  Broward County    RICKS     DEVON   
48595        667         75075    67999  Broward County    RICKS     DEVON   

      MiddleName Sex_Code_Text  Ethnic_Code_Text DateOfBirth  ...  day  year  \
47996    LATRICE        Female  African-American   1/20/1981  ...   20  1981   
47995    LATRICE        Female  African-American   1/20/1981  ...   20  1981   
47994    LATRICE        Female  African-American   1/20/1981  ...   20  1981   
48596        NaN          Male  African-American  11/25/1988  ...   25  1988   
48595        NaN          Male  African-American  11/25/1988  ...   25  1988   

              dob      scrdte age ID_CUMCNT gender1 Language_1  \
47996  1981-01-20  2014-07-13  33         0       1          0   
47995  1981-01-20  2014-07-13  33         1       1          0   
47994  1981-01-20  2014-07-13  33         2       1          0   
48596  1988-11-25  2014-07-20  26         0       0          0   
48595  1988-11-25  2014-07-20  26         1       0          0   

       MaritalStatusBinary EthnicCodeEncoded  
47996                    0                 0  
47995                    0                 0  
47994                    0                 0  
48596                    0                 0  
48595                    0                 0  

[5 rows x 39 columns]

In [35]:
cp2['CustodyStatus'].value_counts()

CustodyStatus
Jail Inmate            27707
Probation              20959
Pretrial Defendant      7032
Residential Program       59
Parole                    21
Prison Inmate             15
Name: count, dtype: int64

In [36]:
custody_status_mapping = {
    'Jail Inmate': 0,
    'Probation': 1,
    'Pretrial Defendant': 2,
    'Residential Program': 3,
    'Parole': 4,
    'Prison Inmate': 5
}

# Apply the mapping
cp2['CustodyStatusEncoded'] = cp2['CustodyStatus'].map(custody_status_mapping)

C:\Users\pablo\AppData\Local\Temp\ipykernel_10220\1295392677.py:11: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cp2['CustodyStatusEncoded'] = cp2['CustodyStatus'].map(custody_status_mapping)


## Final Base Data Dictionary

In [37]:
print("Now we have converted all the categorical features into numerical features in new columns.")
cp2

Now we have converted all the categorical features into numerical features in new columns.


Person_ID  AssessmentID  Case_ID     Agency_Text LastName FirstName  \
47996        656         74859      350  Broward County    DAVIS   LAKISHA   
47995        656         74859      350  Broward County    DAVIS   LAKISHA   
47994        656         74859      350  Broward County    DAVIS   LAKISHA   
48596        667         75075    67999  Broward County    RICKS     DEVON   
48595        667         75075    67999  Broward County    RICKS     DEVON   
...          ...           ...      ...             ...      ...       ...   
60793      68604         79671    72043        PRETRIAL  Sookram   krishna   
60792      68604         79671    72043        PRETRIAL  Sookram   krishna   
60827      68608         79677    72045        PRETRIAL    Hayes    Thomas   
60826      68608         79677    72045        PRETRIAL    Hayes    Thomas   
60825      68608         79677    72045        PRETRIAL    Hayes    Thomas   

      MiddleName Sex_Code_Text  Ethnic_Code_Text DateOfBirth  ...  year  \
47996    LATRICE        Female  African-American   1/20/1981  ...  1981   
47995    LATRICE        Female  African-American   1/20/1981  ...  1981   
47994    LATRICE        Female  African-American   1/20/1981  ...  1981   
48596        NaN          Male  African-American  11/25/1988  ...  1988   
48595        NaN          Male  African-American  11/25/1988  ...  1988   
...          ...           ...               ...         ...  ...   ...   
60793        NaN          Male         Caucasian   8/15/1984  ...  1984   
60792        NaN          Male         Caucasian   8/15/1984  ...  1984   
60827        NaN          Male         Caucasian   8/13/1989  ...  1989   
60826        NaN          Male         Caucasian   8/13/1989  ...  1989   
60825        NaN          Male         Caucasian   8/13/1989  ...  1989   

              dob      scrdte age ID_CUMCNT gender1 Language_1  \
47996  1981-01-20  2014-07-13  33         0       1          0   
47995  1981-01-20  2014-07-13  33         1       1          0   
47994  1981-01-20  2014-07-13  33         2       1          0   
48596  1988-11-25  2014-07-20  26         0       0          0   
48595  1988-11-25  2014-07-20  26         1       0          0   
...           ...         ...  ..       ...     ...        ...   
60793  1984-08-15  2014-12-31  30         1       0          0   
60792  1984-08-15  2014-12-31  30         2       0          0   
60827  1989-08-13  2014-12-31  25         0       0          0   
60826  1989-08-13  2014-12-31  25         1       0          0   
60825  1989-08-13  2014-12-31  25         2       0          0   

      MaritalStatusBinary  EthnicCodeEncoded CustodyStatusEncoded  
47996                   0                  0                    0  
47995                   0                  0                    0  
47994                   0                  0                    0  
48596                   0                  0                    0  
48595                   0                  0                    0  
...                   ...                ...                  ...  
60793                   0                  1                    0  
60792                   0                  1                    0  
60827                   0                  1                    0  
60826                   0                  1                    0  
60825                   0                  1                    0  

[55793 rows x 40 columns]

In [38]:
cprfa=cp2[(cp2.DisplayText=='Risk of Failure to Appear') & (cp2.ID_CUMCNT==0)]
cpror=cp2[(cp2.DisplayText=='Risk of Recidivism') & (cp2.ID_CUMCNT==1)]
cprov=cp2[(cp2.DisplayText=='Risk of Violence') & (cp2.ID_CUMCNT==2)]

## Dictionaries for each risk

In [39]:
cprfa.head()

Person_ID  AssessmentID  Case_ID     Agency_Text LastName FirstName  \
47996        656         74859      350  Broward County    DAVIS   LAKISHA   
48596        667         75075    67999  Broward County    RICKS     DEVON   
57347        684         78389    70936        PRETRIAL   MENDEZ    NELSON   
40121        737         71931      430        PRETRIAL    Sorto      Alan   
40778        745         72187      438        PRETRIAL  johnson  roderick   

      MiddleName Sex_Code_Text  Ethnic_Code_Text DateOfBirth  ...  year  \
47996    LATRICE        Female  African-American   1/20/1981  ...  1981   
48596        NaN          Male  African-American  11/25/1988  ...  1988   
57347      ANDRE        Female         Caucasian   9/21/1981  ...  1981   
40121          J          Male         Caucasian    5/2/1990  ...  1990   
40778        NaN          Male  African-American    9/8/1982  ...  1982   

              dob      scrdte age ID_CUMCNT gender1 Language_1  \
47996  1981-01-20  2014-07-13  33         0       1          0   
48596  1988-11-25  2014-07-20  26         0       0          0   
57347  1981-09-21  2014-11-07  33         0       1          0   
40121  1990-05-02  2014-04-06  24         0       0          0   
40778  1982-09-08  2014-04-13  32         0       0          0   

      MaritalStatusBinary  EthnicCodeEncoded CustodyStatusEncoded  
47996                   0                  0                    0  
48596                   0                  0                    0  
57347                   0                  1                    0  
40121                   0                  1                    0  
40778                   0                  0                    0  

[5 rows x 40 columns]

In [40]:
cpror

Person_ID  AssessmentID  Case_ID     Agency_Text LastName FirstName  \
47995        656         74859      350  Broward County    DAVIS   LAKISHA   
48595        667         75075    67999  Broward County    RICKS     DEVON   
57346        684         78389    70936        PRETRIAL   MENDEZ    NELSON   
40120        737         71931      430        PRETRIAL    Sorto      Alan   
40777        745         72187      438        PRETRIAL  johnson  roderick   
...          ...           ...      ...             ...      ...       ...   
60787      68600         79666    72039        PRETRIAL   Curtis    Cheryl   
60790      68602         79668    72041        PRETRIAL    Avery  Brittany   
60841      68603         79669    72042        PRETRIAL     Ryan   Michael   
60793      68604         79671    72043        PRETRIAL  Sookram   krishna   
60826      68608         79677    72045        PRETRIAL    Hayes    Thomas   

      MiddleName Sex_Code_Text  Ethnic_Code_Text DateOfBirth  ...  year  \
47995    LATRICE        Female  African-American   1/20/1981  ...  1981   
48595        NaN          Male  African-American  11/25/1988  ...  1988   
57346      ANDRE        Female         Caucasian   9/21/1981  ...  1981   
40120          J          Male         Caucasian    5/2/1990  ...  1990   
40777        NaN          Male  African-American    9/8/1982  ...  1982   
...          ...           ...               ...         ...  ...   ...   
60787          A        Female         Caucasian   1/20/1969  ...  1969   
60790        NaN        Female         Caucasian   6/26/1994  ...  1994   
60841        NaN          Male         Caucasian    2/6/1985  ...  1985   
60793        NaN          Male         Caucasian   8/15/1984  ...  1984   
60826        NaN          Male         Caucasian   8/13/1989  ...  1989   

              dob      scrdte age ID_CUMCNT gender1 Language_1  \
47995  1981-01-20  2014-07-13  33         1       1          0   
48595  1988-11-25  2014-07-20  26         1       0          0   
57346  1981-09-21  2014-11-07  33         1       1          0   
40120  1990-05-02  2014-04-06  24         1       0          0   
40777  1982-09-08  2014-04-13  32         1       0          0   
...           ...         ...  ..       ...     ...        ...   
60787  1969-01-20  2014-12-31  46         1       1          0   
60790  1994-06-26  2014-12-31  21         1       1          0   
60841  1985-02-06  2014-12-31  30         1       0          0   
60793  1984-08-15  2014-12-31  30         1       0          0   
60826  1989-08-13  2014-12-31  25         1       0          0   

      MaritalStatusBinary  EthnicCodeEncoded CustodyStatusEncoded  
47995                   0                  0                    0  
48595                   0                  0                    0  
57346                   0                  1                    0  
40120                   0                  1                    0  
40777                   0                  0                    0  
...                   ...                ...                  ...  
60787                   0                  1                    0  
60790                   0                  1                    2  
60841                   0                  1                    0  
60793                   0                  1                    0  
60826                   0                  1                    0  

[18427 rows x 40 columns]

In [41]:
cpror[cpror['FirstName'] == 'Kurt']

Person_ID  AssessmentID  Case_ID Agency_Text LastName FirstName  \
60814      34047         79654    33181    PRETRIAL    Lewis      Kurt   
8077       35617         60162    54648   Probation    Brown      Kurt   
7864       53106         60037    54534   Probation    Fowks      Kurt   
8611       53306         60291    54761    PRETRIAL  Vanasse      Kurt   
41290      62833         72371    65605   Probation    Brown      Kurt   

      MiddleName Sex_Code_Text  Ethnic_Code_Text DateOfBirth  ...  year  \
60814        NaN          Male             Other    8/3/1974  ...  1974   
8077   Walterlee          Male  African-American    3/3/1980  ...  1980   
7864         NaN          Male         Caucasian   2/11/1990  ...  1990   
8611         NaN          Male         Caucasian   8/16/1969  ...  1969   
41290        NaN          Male  African-American    3/3/1980  ...  1980   

              dob      scrdte age ID_CUMCNT gender1 Language_1  \
60814  1974-08-03  2014-12-31  40         1       0          0   
8077   1980-03-03  2013-03-21  33         1       0          0   
7864   1990-02-11  2013-03-19  23         1       0          0   
8611   1969-08-16  2013-03-25  44         1       0          0   
41290  1980-03-03  2014-04-18  34         1       0          0   

      MaritalStatusBinary  EthnicCodeEncoded CustodyStatusEncoded  
60814                   0                  4                    0  
8077                    0                  0                    1  
7864                    0                  1                    1  
8611                    0                  1                    0  
41290                   0                  0                    1  

[5 rows x 40 columns]

In [42]:
cprov.head()

Person_ID  AssessmentID  Case_ID     Agency_Text LastName FirstName  \
47994        656         74859      350  Broward County    DAVIS   LAKISHA   
48594        667         75075    67999  Broward County    RICKS     DEVON   
57345        684         78389    70936        PRETRIAL   MENDEZ    NELSON   
40119        737         71931      430        PRETRIAL    Sorto      Alan   
40776        745         72187      438        PRETRIAL  johnson  roderick   

      MiddleName Sex_Code_Text  Ethnic_Code_Text DateOfBirth  ...  year  \
47994    LATRICE        Female  African-American   1/20/1981  ...  1981   
48594        NaN          Male  African-American  11/25/1988  ...  1988   
57345      ANDRE        Female         Caucasian   9/21/1981  ...  1981   
40119          J          Male         Caucasian    5/2/1990  ...  1990   
40776        NaN          Male  African-American    9/8/1982  ...  1982   

              dob      scrdte age ID_CUMCNT gender1 Language_1  \
47994  1981-01-20  2014-07-13  33         2       1          0   
48594  1988-11-25  2014-07-20  26         2       0          0   
57345  1981-09-21  2014-11-07  33         2       1          0   
40119  1990-05-02  2014-04-06  24         2       0          0   
40776  1982-09-08  2014-04-13  32         2       0          0   

      MaritalStatusBinary  EthnicCodeEncoded CustodyStatusEncoded  
47994                   0                  0                    0  
48594                   0                  0                    0  
57345                   0                  1                    0  
40119                   0                  1                    0  
40776                   0                  0                    0  

[5 rows x 40 columns]

In [43]:
cp2.columns

Index(['Person_ID', 'AssessmentID', 'Case_ID', 'Agency_Text', 'LastName',
       'FirstName', 'MiddleName', 'Sex_Code_Text', 'Ethnic_Code_Text',
       'DateOfBirth', 'ScaleSet_ID', 'ScaleSet', 'AssessmentReason',
       'Language', 'LegalStatus', 'CustodyStatus', 'MaritalStatus',
       'Screening_Date', 'RecSupervisionLevel', 'RecSupervisionLevelText',
       'Scale_ID', 'DisplayText', 'RawScore', 'DecileScore', 'ScoreText',
       'AssessmentType', 'IsCompleted', 'IsDeleted', 'month', 'day', 'year',
       'dob', 'scrdte', 'age', 'ID_CUMCNT', 'gender1', 'Language_1',
       'MaritalStatusBinary', 'EthnicCodeEncoded', 'CustodyStatusEncoded'],
      dtype='object')

# Data Profile-compas.raw

In [44]:
print('Use the dtypes function to generate a base dataframe with all of the column names and dtypes.')
cp_dictionary=pd.DataFrame(cp.dtypes).reset_index().reset_index().rename(columns={'level_0':'COLIDX','index':'COLNAME',0:'COL_DTYPE'})
cp_dictionary['COLDESCRIPT']=' '
cpnullpct=pd.DataFrame(cp.isnull().sum()/cp.shape[0]).reset_index().reset_index().rename(columns={'level_0':'COLIDX','index':'COLNAME',0:'NULLPCT'})
cpnullpct['NULLPCT']=cpnullpct.NULLPCT.map("{:.2%}".format)
cp_dictionary1=cp_dictionary.merge(cpnullpct,on=['COLIDX','COLNAME'])
print('Display compas_raw1(cp) data dictionary.')
cp_dictionary1

Use the dtypes function to generate a base dataframe with all of the column names and dtypes.
Display compas_raw1(cp) data dictionary.


COLIDX                  COLNAME COL_DTYPE COLDESCRIPT NULLPCT
0        0                Person_ID     int64               0.00%
1        1             AssessmentID     int64               0.00%
2        2                  Case_ID     int64               0.00%
3        3              Agency_Text    object               0.00%
4        4                 LastName    object               0.00%
5        5                FirstName    object               0.00%
6        6               MiddleName    object              74.32%
7        7            Sex_Code_Text    object               0.00%
8        8         Ethnic_Code_Text    object               0.00%
9        9              DateOfBirth    object               0.00%
10      10              ScaleSet_ID     int64               0.00%
11      11                 ScaleSet    object               0.00%
12      12         AssessmentReason    object               0.00%
13      13                 Language    object               0.00%
14      14              LegalStatus    object               0.00%
15      15            CustodyStatus    object               0.00%
16      16            MaritalStatus    object               0.00%
17      17           Screening_Date    object               0.00%
18      18      RecSupervisionLevel     int64               0.00%
19      19  RecSupervisionLevelText    object               0.00%
20      20                 Scale_ID     int64               0.00%
21      21              DisplayText    object               0.00%
22      22                 RawScore   float64               0.00%
23      23              DecileScore     int64               0.00%
24      24                ScoreText    object               0.00%
25      25           AssessmentType    object               0.00%
26      26              IsCompleted     int64               0.00%
27      27                IsDeleted     int64               0.00%
28      28                    month    object               0.00%
29      29                      day    object               0.00%
30      30                     year    object               0.00%
31      31                      dob    object               0.00%
32      32                   scrdte    object               0.00%
33      33                      age     int32               0.00%

In [45]:
print('Reorder the columns for ease of information interpretation.')
cp_dictionary1=cp_dictionary1.iloc[:,[0,1,3,2,4]]
cp_dictionary1

Reorder the columns for ease of information interpretation.


COLIDX                  COLNAME COLDESCRIPT COL_DTYPE NULLPCT
0        0                Person_ID                 int64   0.00%
1        1             AssessmentID                 int64   0.00%
2        2                  Case_ID                 int64   0.00%
3        3              Agency_Text                object   0.00%
4        4                 LastName                object   0.00%
5        5                FirstName                object   0.00%
6        6               MiddleName                object  74.32%
7        7            Sex_Code_Text                object   0.00%
8        8         Ethnic_Code_Text                object   0.00%
9        9              DateOfBirth                object   0.00%
10      10              ScaleSet_ID                 int64   0.00%
11      11                 ScaleSet                object   0.00%
12      12         AssessmentReason                object   0.00%
13      13                 Language                object   0.00%
14      14              LegalStatus                object   0.00%
15      15            CustodyStatus                object   0.00%
16      16            MaritalStatus                object   0.00%
17      17           Screening_Date                object   0.00%
18      18      RecSupervisionLevel                 int64   0.00%
19      19  RecSupervisionLevelText                object   0.00%
20      20                 Scale_ID                 int64   0.00%
21      21              DisplayText                object   0.00%
22      22                 RawScore               float64   0.00%
23      23              DecileScore                 int64   0.00%
24      24                ScoreText                object   0.00%
25      25           AssessmentType                object   0.00%
26      26              IsCompleted                 int64   0.00%
27      27                IsDeleted                 int64   0.00%
28      28                    month                object   0.00%
29      29                      day                object   0.00%
30      30                     year                object   0.00%
31      31                      dob                object   0.00%
32      32                   scrdte                object   0.00%
33      33                      age                 int32   0.00%

In [46]:
print('Hint: Use a Python dictionary to add descriptions to your dictionary file.')
cpdescribe=cp.describe(include='all')
cpdescribe1=cpdescribe.transpose().reset_index().rename(columns={'index':'COLNAME','count':'COLCNT'})
cp_dictionary2=cp_dictionary1.merge(cpdescribe1,how='outer',on='COLNAME')
cp_dictionary2['COLCNT']=cp_dictionary2.COLCNT.astype('int')
cp_dictionary2

Hint: Use a Python dictionary to add descriptions to your dictionary file.


COLIDX                  COLNAME COLDESCRIPT COL_DTYPE NULLPCT  COLCNT  \
0        0                Person_ID                 int64   0.00%   60798   
1        1             AssessmentID                 int64   0.00%   60798   
2        2                  Case_ID                 int64   0.00%   60798   
3        3              Agency_Text                object   0.00%   60798   
4        4                 LastName                object   0.00%   60798   
5        5                FirstName                object   0.00%   60798   
6        6               MiddleName                object  74.32%   15615   
7        7            Sex_Code_Text                object   0.00%   60798   
8        8         Ethnic_Code_Text                object   0.00%   60798   
9        9              DateOfBirth                object   0.00%   60798   
10      10              ScaleSet_ID                 int64   0.00%   60798   
11      11                 ScaleSet                object   0.00%   60798   
12      12         AssessmentReason                object   0.00%   60798   
13      13                 Language                object   0.00%   60798   
14      14              LegalStatus                object   0.00%   60798   
15      15            CustodyStatus                object   0.00%   60798   
16      16            MaritalStatus                object   0.00%   60798   
17      17           Screening_Date                object   0.00%   60798   
18      18      RecSupervisionLevel                 int64   0.00%   60798   
19      19  RecSupervisionLevelText                object   0.00%   60798   
20      20                 Scale_ID                 int64   0.00%   60798   
21      21              DisplayText                object   0.00%   60798   
22      22                 RawScore               float64   0.00%   60798   
23      23              DecileScore                 int64   0.00%   60798   
24      24                ScoreText                object   0.00%   60798   
25      25           AssessmentType                object   0.00%   60798   
26      26              IsCompleted                 int64   0.00%   60798   
27      27                IsDeleted                 int64   0.00%   60798   
28      28                    month                object   0.00%   60798   
29      29                      day                object   0.00%   60798   
30      30                     year                object   0.00%   60798   
31      31                      dob                object   0.00%   60798   
32      32                   scrdte                object   0.00%   60798   
33      33                      age                 int32   0.00%   60798   

   unique                        top   freq          mean           std  \
0     NaN                        NaN    NaN  53682.065808  14367.201275   
1     NaN                        NaN    NaN  68062.709958   7321.241459   
2     NaN                        NaN    NaN  60210.451018   9639.641168   
3       4                   PRETRIAL  41077           NaN           NaN   
4   10896                   Williams    417           NaN           NaN   
5    7225                    Michael    775           NaN           NaN   
6    1870                          A    604           NaN           NaN   
7       2                       Male  47479           NaN           NaN   
8       9           African-American  27002           NaN           NaN   
9   10382                   1/3/1986     30           NaN           NaN   
10    NaN                        NaN    NaN     21.819402      0.932946   
11      2         Risk and Prescreen  58602           NaN           NaN   
12      1                     Intake  60798           NaN           NaN   
13      2                    English  60546           NaN           NaN   
14      7                   Pretrial  37557           NaN           NaN   
15      6                Jail Inmate  30116           NaN           NaN   
16      7                     Sin

### QA Profile

In [47]:
#numeric_columns = ['RecSupervisionLevel', 'age', 'gender1', 'Language_1',
                   #'MaritalStatusBinary', 'EthnicCodeEncoded', 'CustodyStatusEncoded']
#mean_profile = cp2.groupby('DecileScore')[numeric_columns].mean()
#mean_profile

RecSupervisionLevel        age   gender1  Language_1  \
DecileScore                                                         
1                       1.118554  40.675918  0.245046    0.006682   
2                       1.242453  33.749038  0.232778    0.005362   
3                       1.381080  32.169156  0.213839    0.005617   
4                       1.460939  30.339143  0.273119    0.003076   
5                       1.594209  30.302646  0.207193    0.002714   
6                       2.130670  30.191237  0.216237    0.001546   
7                       2.226644  30.233052  0.185497    0.001349   
8                       3.078893  30.258571  0.154069    0.000413   
9                       3.298530  29.806893  0.174354    0.000507   
10                      3.467367  29.609902  0.132783    0.000000   

             MaritalStatusBinary  EthnicCodeEncoded  CustodyStatusEncoded  
DecileScore                                                                
1                       0.266861           1.122038              0.645480  
2                       0.166220           0.963982              0.633174  
3                       0.123707           0.862888              0.642538  
4                       0.099446           0.805618              0.652245  
5                       0.093644           0.717937              0.611400  
6                       0.083247           0.642268              0.635309  
7                       0.069140           0.584486              0.597302  
8                       0.066501           0.504337              0.606361  
9                       0.056766           0.458186              0.609731  
10                      0.049512           0.451613              0.600150

# Data Profile- two_year_redicivism

In [48]:
df=pd.read_csv('two_year_recidivism.csv')
df.info(verbose=True)
df

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4743 entries, 0 to 4742
Data columns (total 54 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   id                       4743 non-null   int64  
 1   name                     4743 non-null   object 
 2   first                    4743 non-null   object 
 3   last                     4743 non-null   object 
 4   compas_screening_date    4743 non-null   object 
 5   sex                      4743 non-null   object 
 6   dob                      4743 non-null   object 
 7   age                      4743 non-null   int64  
 8   age_cat                  4743 non-null   object 
 9   race                     4743 non-null   object 
 10  juv_fel_count            4743 non-null   int64  
 11  decile_score             4743 non-null   int64  
 12  juv_misd_count           4743 non-null   int64  
 13  juv_other_count          4743 non-null   int64  
 14  priors_count            

id                name    first         last compas_screening_date  \
0         1    miguel hernandez   miguel    hernandez             8/14/2013   
1         3         kevon dixon    kevon        dixon             1/27/2013   
2         5         marcu brown    marcu        brown             1/13/2013   
3         6  bouthy pierrelouis   bouthy  pierrelouis             3/26/2013   
4         7        marsha miles   marsha        miles            11/30/2013   
...     ...                 ...      ...          ...                   ...   
4738  10995        raheem smith   raheem        smith            10/20/2013   
4739  10996       steven butler   steven       butler            11/23/2013   
4740  10997     malcolm simmons  malcolm      simmons              2/1/2014   
4741  10999     winston gregory  winston      gregory             1/14/2014   
4742  11000         farrah jean   farrah         jean              3/9/2014   

         sex         dob  age          age_cat              race  ...  \
0       Male   4/18/1947   69  Greater than 45             Other  ...   
1       Male   1/22/1982   34          25 - 45  African-American  ...   
2       Male   1/21/1993   23     Less than 25  African-American  ...   
3       Male   1/22/1973   43          25 - 45             Other  ...   
4       Male   8/22/1971   44          25 - 45             Other  ...   
...      ...         ...  ...              ...               ...  ...   
4738    Male   6/28/1995   20     Less than 25  African-American  ...   
4739    Male   7/17/1992   23     Less than 25  African-American  ...   
4740    Male   3/25/1993   23     Less than 25  African-American  ...   
4741    Male   10/1/1958   57  Greater than 45             Other  ...   
4742  Female  11/17/1982   33          25 - 45  African-American  ...   

      v_score_text  v_screening_date  in_custody  out_custody  priors_count.1  \
0              Low         8/14/2013    7/7/2014    7/14/2014               0   
1              Low         1/27/2013   1/26/2013     2/5/2013               0   
2           Medium         1/13/2013         NaN          NaN               1   
3              Low         3/26/2013         NaN          NaN               2   
4              Low        11/30/2013  11/30/2013    12/1/2013               0   
...            ...               ...         ...          ...             ...   
4738          High        10/20/2013    4/7/2014    4/27/2014               0   
4739        Medium        11/23/2013  11/22/2013   11/24/2013               0   
4740        Medium          2/1/2014   1/31/2014     2/2/2014               0   
4741           Low         1/14/2014   1/13/2014    1/14/2014               0   
4742           Low          3/9/2014    3/8/2014     3/9/2014               3   

      start   end event two_year_recid two_year_recid.1  
0         0   327     0              0                0  
1         9   159     1              1                1  
2         0  1174     0              0                0  
3         0  1102     0              0                0  
4         1   853     0              0                0  
...     ...   ...   ...            ...              ...  
4738      0   169     0              0                0  
4739      1   860     0              0                0  
4740      1   790     0              0                0  
4741      0   808     0              0                0  
4742      0   754     0              0                0  

[4743 rows x 54 columns]

In [49]:
print('Use the dtypes function to generate a base dataframe with all of the column names and dtypes.')
df_dictionary = pd.DataFrame(df.dtypes).reset_index().reset_index().rename(columns={'level_0': 'COLIDX', 'index': 'COLNAME', 0: 'COL_DTYPE'})
df_dictionary['COLDESCRIPT'] = ' '
df_nullpct = pd.DataFrame(df.isnull().sum() / df.shape[0]).reset_index().reset_index().rename(columns={'level_0': 'COLIDX', 'index': 'COLNAME', 0: 'NULLPCT'})
df_nullpct['NULLPCT'] = df_nullpct.NULLPCT.map("{:.2%}".format)
df_dictionary1 = df_dictionary.merge(df_nullpct, on=['COLIDX', 'COLNAME'])
print('Display two_year_recidivism.csv (df) data dictionary.')
df_dictionary1=df_dictionary1.iloc[:,[0,1,3,2,4]]
df_dictionary1

Use the dtypes function to generate a base dataframe with all of the column names and dtypes.
Display two_year_recidivism.csv (df) data dictionary.


COLIDX                  COLNAME COLDESCRIPT COL_DTYPE  NULLPCT
0        0                       id                 int64    0.00%
1        1                     name                object    0.00%
2        2                    first                object    0.00%
3        3                     last                object    0.00%
4        4    compas_screening_date                object    0.00%
5        5                      sex                object    0.00%
6        6                      dob                object    0.00%
7        7                      age                 int64    0.00%
8        8                  age_cat                object    0.00%
9        9                     race                object    0.00%
10      10            juv_fel_count                 int64    0.00%
11      11             decile_score                 int64    0.00%
12      12           juv_misd_count                 int64    0.00%
13      13          juv_other_count                 int64    0.00%
14      14             priors_count                 int64    0.00%
15      15  days_b_screening_arrest               float64    5.65%
16      16                c_jail_in                object    5.65%
17      17               c_jail_out                object    5.65%
18      18            c_case_number                object    0.23%
19      19           c_offense_date                object   16.26%
20      20            c_arrest_date                object   83.98%
21      21       c_days_from_compas               float64    0.23%
22      22          c_charge_degree                object    0.00%
23      23            c_charge_desc                object    0.36%
24      24                 is_recid                 int64    0.00%
25      25            r_case_number                object   79.02%
26      26          r_charge_degree                object   79.02%
27      27       r_days_from_arrest               float64   85.45%
28      28           r_offense_date                object   79.02%
29      29            r_charge_desc                object   79.51%
30      30                r_jail_in                object   85.45%
31      31               r_jail_out                object   85.45%
32      32            violent_recid               float64  100.00%
33      33         is_violent_recid                 int64    0.00%
34      34           vr_case_number                object   82.73%
35      35         vr_charge_degree                object   82.73%
36      36          vr_offense_date                object   82.73%
37      37           vr_charge_desc                object   82.73%
38      38       type_of_assessment                object    0.00%
39      39           decile_score.1                 int64    0.00%
40      40               score_text                object    0.11%
41      41           screening_date                object    0.00%
42      42     v_type_of_assessment                object    0.00%
43      43           v_decile_score                 int64    0.00%
44      44             v_score_text                object    0.00%
45      45         v_screening_date                object    0.00%
46      46               in_custody                object    4.41%
47      47              out_custody                object    4.41%
48      48           priors_count.1                 int64    0.00%
49      49                    start                 int64    0.00%
50      50                      end                 int64    0.00%
51      51                    event                 int64    0.00%
52      52           two_year_recid                 int64    0.00%
53      53         two_year_recid.1                 int64    0.00%

# QA- two_year_redicivism.csv

In [50]:
df.columns

Index(['id', 'name', 'first', 'last', 'compas_screening_date', 'sex', 'dob',
       'age', 'age_cat', 'race', 'juv_fel_count', 'decile_score',
       'juv_misd_count', 'juv_other_count', 'priors_count',
       'days_b_screening_arrest', 'c_jail_in', 'c_jail_out', 'c_case_number',
       'c_offense_date', 'c_arrest_date', 'c_days_from_compas',
       'c_charge_degree', 'c_charge_desc', 'is_recid', 'r_case_number',
       'r_charge_degree', 'r_days_from_arrest', 'r_offense_date',
       'r_charge_desc', 'r_jail_in', 'r_jail_out', 'violent_recid',
       'is_violent_recid', 'vr_case_number', 'vr_charge_degree',
       'vr_offense_date', 'vr_charge_desc', 'type_of_assessment',
       'decile_score.1', 'score_text', 'screening_date',
       'v_type_of_assessment', 'v_decile_score', 'v_score_text',
       'v_screening_date', 'in_custody', 'out_custody', 'priors_count.1',
       'start', 'end', 'event', 'two_year_recid', 'two_year_recid.1'],
      dtype='object')

Check for 1 to many problem in  "id" column

In [51]:
df.duplicated(subset=['id']).sum()

0

In [52]:
duplicates_by_name = df[df['name'] == 'bouthy pierrelouis']

# Count the number of entries with the name "bouthy pierrelouis"
duplicate_count_by_name = len(duplicates_by_name)

print(duplicate_count_by_name)

1


In [53]:
df.isnull().sum()

id                            0
name                          0
first                         0
last                          0
compas_screening_date         0
sex                           0
dob                           0
age                           0
age_cat                       0
race                          0
juv_fel_count                 0
decile_score                  0
juv_misd_count                0
juv_other_count               0
priors_count                  0
days_b_screening_arrest     268
c_jail_in                   268
c_jail_out                  268
c_case_number                11
c_offense_date              771
c_arrest_date              3983
c_days_from_compas           11
c_charge_degree               0
c_charge_desc                17
is_recid                      0
r_case_number              3748
r_charge_degree            3748
r_days_from_arrest         4053
r_offense_date             3748
r_charge_desc              3771
r_jail_in                  4053
r_jail_o

In [54]:
df['name'].value_counts()

name
jeffrey jackson     2
angel santiago      2
michael flores      2
carlos vasquez      2
michael davis       2
                   ..
donny evans         1
julio salem         1
emad abdelquader    1
steven corey        1
farrah jean         1
Name: count, Length: 4721, dtype: int64

In [55]:
df.duplicated(subset=['id']).sum()



0

In [56]:
df['decile_score'].unique()

array([ 1,  3,  8,  4, 10,  5,  2,  7,  9,  6, -1], dtype=int64)

In [57]:
df[df['decile_score']==-1]

id                 name    first         last compas_screening_date  \
1650  3708          katt mcnish     katt       mcnish             5/12/2013   
2183  4995  raymond manganiotis  raymond  manganiotis             6/21/2013   
2733  6283          carla silva    carla        silva             9/23/2013   
3089  7132            clee farr     clee         farr              2/8/2013   
3788  8766   william winkelmann  william   winkelmann             4/24/2013   

         sex         dob  age          age_cat       race  ...  v_score_text  \
1650  Female   5/14/1976   39          25 - 45  Caucasian  ...           Low   
2183    Male   1/25/1963   53  Greater than 45  Caucasian  ...           Low   
2733  Female    3/1/1954   62  Greater than 45      Other  ...           Low   
3089    Male  12/22/1955   60  Greater than 45  Caucasian  ...        Medium   
3788    Male  12/15/1953   62  Greater than 45  Caucasian  ...           Low   

      v_screening_date  in_custody  out_custody  priors_count.1  start   end  \
1650         5/12/2013   5/11/2013    5/12/2013               0      0  1055   
2183         6/21/2013   6/11/2013    6/21/2013               3      0  1015   
2733         9/23/2013   9/21/2013    9/22/2013               1      0   921   
3089          2/8/2013    2/7/2013     2/8/2013               0      0  1148   
3788         4/24/2013    4/4/2013     4/5/2013               2      0  1073   

     event two_year_recid two_year_recid.1  
1650     0              0                0  
2183     0              0                0  
2733     0              0                0  
3089     0              0                0  
3788     0              0                0  

[5 rows x 54 columns]

In [58]:
df.sample()

id             name  first       last compas_screening_date   sex  \
2125  4847  tracy gallagher  tracy  gallagher             2/16/2013  Male   

           dob  age          age_cat       race  ...  v_score_text  \
2125  4/1/1966   50  Greater than 45  Caucasian  ...        Medium   

      v_screening_date  in_custody  out_custody  priors_count.1  start  end  \
2125         2/16/2013   2/16/2013    3/13/2013               3     25  690   

     event two_year_recid two_year_recid.1  
2125     1              1                1  

[1 rows x 54 columns]

In [59]:
df['type_of_assessment'].unique()

array(['Risk of Recidivism'], dtype=object)

In [60]:
df.rename(columns={
    'first': 'FirstName',
    'last': 'LastName',
    'dob': 'DateOfBirth',
    'sex': 'Sex_Code_Text'
}, inplace=True)

Notice that the first and last names in the second dataset are in lowercase only, let's fix that for enhanced match rate.

In [61]:
cpror[['FirstName', 'LastName']] = cpror[['FirstName', 'LastName']].apply(lambda x: x.str.lower())

C:\Users\pablo\AppData\Local\Temp\ipykernel_10220\3520444572.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cpror[['FirstName', 'LastName']] = cpror[['FirstName', 'LastName']].apply(lambda x: x.str.lower())


In [62]:
cpror.shape

(18427, 40)

In [63]:
df.shape

(4743, 54)

# Answer the following questions prior to your merge
how many columns and rows did you expect in your final file? Why? What type of join/merge did you use (inner or outer, left or right)


1. How many columns and rows did you expect in your final file? Why?

Initially, I used an inner join to merge the compas_raw and two_year_recidivism datasets based on the keys FirstName, LastName, DateOfBirth, and Sex_Code_Text. This resulted in a final dataset that only included individuals present in both datasets, which meant only those who re-offended were retained. While this approach ensured that all rows in the merged dataset had corresponding matches, it excluded non-reoffending individuals, which introduced bias and limited the ability to evaluate the ROR (Release on Recognizance) model's performance across the full population.

To ensure a comprehensive analysis, I switched to an outer left join, which retained all rows from compas_raw (18,427 rows) while adding matching information from two_year_recidivism (4,743 rows). This approach preserved non-reoffending individuals in the final dataset, making it possible to evaluate the ROR model's performance fairly and without bias.

The final merged dataset consisted of 18,427 rows and 90 columns, providing a complete view of both reoffending and non-reoffending individuals for analysis.

2. What type of join/merge did you use (inner, outer, left, or right)?

I initially used an inner join to merge the datasets, but after reviewing the limitations of this approach, I switched to an outer left join. This type of join ensured that all rows from the compas_raw dataset (18,427 rows) were retained in the final merged file, regardless of whether there was a matching row in the two_year_recidivism dataset (4,743 rows). The outer left join preserved non-reoffending individuals, allowing for a comprehensive evaluation of the dataset and the ROR model's performance. The final merged file contained 18,427 rows and 90 columns.

In [72]:
merge = pd.merge(cpror,df , on=['FirstName', 'LastName', 'DateOfBirth', 'Sex_Code_Text'], how='left')
merge

Person_ID  AssessmentID  Case_ID     Agency_Text LastName FirstName  \
0            656         74859      350  Broward County    davis   lakisha   
1            667         75075    67999  Broward County    ricks     devon   
2            684         78389    70936        PRETRIAL   mendez    nelson   
3            737         71931      430        PRETRIAL    sorto      alan   
4            745         72187      438        PRETRIAL  johnson  roderick   
...          ...           ...      ...             ...      ...       ...   
18422      68600         79666    72039        PRETRIAL   curtis    cheryl   
18423      68602         79668    72041        PRETRIAL    avery  brittany   
18424      68603         79669    72042        PRETRIAL     ryan   michael   
18425      68604         79671    72043        PRETRIAL  sookram   krishna   
18426      68608         79677    72045        PRETRIAL    hayes    thomas   

      MiddleName Sex_Code_Text  Ethnic_Code_Text DateOfBirth  ...  \
0        LATRICE        Female  African-American   1/20/1981  ...   
1            NaN          Male  African-American  11/25/1988  ...   
2          ANDRE        Female         Caucasian   9/21/1981  ...   
3              J          Male         Caucasian    5/2/1990  ...   
4            NaN          Male  African-American    9/8/1982  ...   
...          ...           ...               ...         ...  ...   
18422          A        Female         Caucasian   1/20/1969  ...   
18423        NaN        Female         Caucasian   6/26/1994  ...   
18424        NaN          Male         Caucasian    2/6/1985  ...   
18425        NaN          Male         Caucasian   8/15/1984  ...   
18426        NaN          Male         Caucasian   8/13/1989  ...   

       v_score_text v_screening_date in_custody out_custody priors_count.1  \
0               NaN              NaN        NaN         NaN            NaN   
1            Medium        7/20/2014  7/19/2014   8/14/2014            8.0   
2               NaN              NaN        NaN         NaN            NaN   
3            Medium         4/6/2014   4/6/2014    4/6/2014            6.0   
4               NaN              NaN        NaN         NaN            NaN   
...             ...              ...        ...         ...            ...   
18422           NaN              NaN        NaN         NaN            NaN   
18423           NaN              NaN        NaN         NaN            NaN   
18424           NaN              NaN        NaN         NaN            NaN   
18425           NaN              NaN        NaN         NaN            NaN   
18426           NaN              NaN        NaN         NaN            NaN   

      start    end event  two_year_recid two_year_recid.1  
0       NaN    NaN   NaN             NaN              NaN  
1      25.0   44.0   1.0             1.0              1.0  
2       NaN    NaN   NaN             NaN              NaN  
3       0.0  645.0   1.0             1.0              1.0  
4       NaN    NaN   NaN             NaN              NaN  
...     ...    ...   ...             ...              ...  
18422   NaN    NaN   NaN             NaN              NaN  
18423   NaN    NaN   NaN             NaN              NaN  
18424   NaN    NaN   NaN             NaN              NaN  
18425   NaN    NaN   NaN             NaN              NaN  
18426   NaN    NaN   NaN             NaN              NaN  

[18427 rows x 90 columns]

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=3da9e162-d091-4a28-8291-e3fc4ae77bee' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>